version: '3'

services:
  tts-app:
    build: .
    ports:
      - "8080:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/app
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker
  
  celery-worker:
    build: .
    command: bash -c "cd /app && celery -A celery_config worker --loglevel=info"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/app
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: 