version: '3'

services:
  tts-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./shared_data:/app/shared_data
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker
  
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A celery_config.celery worker --loglevel=info
    working_dir: /app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./shared_data:/app/shared_data
      - .:/app/root_dir
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  shared_data: 