version: '3'

services:
  tts-app:
    image: zpfsmile/azure-speech-transcriber:latest
    ports:
      - "9527:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker
  
  celery-worker:
    image: zpfsmile/azure-speech-transcriber:latest
    command: celery -A celery_app worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
    depends_on:
      - redis
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: 