app = "azure-speech-transcriber"
primary_region = "nrt"  # 东京区域，可根据需要更改

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "app.py"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["web"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["worker"]

[processes]
  web = "gunicorn -b 0.0.0.0:5000 app:app"
  worker = "celery -A app.celery_app worker --loglevel=info" 